02/06/2021 11:32:19 AM  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
02/06/2021 11:32:41 AM successfully connected to backend
02/06/2021 11:32:41 AM 127.0.0.1 - - [06/Feb/2021 11:32:41] "[37mGET /home HTTP/1.1[0m" 200 -
02/06/2021 11:32:41 AM 127.0.0.1 - - [06/Feb/2021 11:32:41] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
02/06/2021 11:35:16 AM successfully connected to backend
02/06/2021 11:35:16 AM 127.0.0.1 - - [06/Feb/2021 11:35:16] "[37mGET /home HTTP/1.1[0m" 200 -
02/06/2021 11:35:16 AM 127.0.0.1 - - [06/Feb/2021 11:35:16] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
02/06/2021 12:41:51 PM  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
02/06/2021 12:42:31 PM 127.0.0.1 - - [06/Feb/2021 12:42:31] "[31m[1mGET /get_info?name=koushik HTTP/1.1[0m" 405 -
02/06/2021 02:21:29 PM  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
02/06/2021 02:22:04 PM 127.0.0.1 - - [06/Feb/2021 14:22:04] "[31m[1mGET /get_info?name=koushik HTTP/1.1[0m" 405 -
02/06/2021 02:22:04 PM 127.0.0.1 - - [06/Feb/2021 14:22:04] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
02/06/2021 02:28:25 PM 127.0.0.1 - - [06/Feb/2021 14:28:25] "[33mPOST / HTTP/1.1[0m" 404 -
02/06/2021 02:28:37 PM Exception on /get_info [POST]
Traceback (most recent call last):
  File "/home/koushik/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/koushik/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/koushik/.local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/koushik/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/koushik/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/koushik/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/koushik/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/koushik/Documents/projects/simple-flask-api/app/routes.py", line 24, in get_info
    return jsonify({"name":name, "age":"28", "n_chars":str(len(name))})
TypeError: object of type 'NoneType' has no len()
02/06/2021 02:28:37 PM 127.0.0.1 - - [06/Feb/2021 14:28:37] "[35m[1mPOST /get_info HTTP/1.1[0m" 500 -
02/06/2021 02:33:47 PM  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
02/06/2021 02:33:47 PM  * Restarting with stat
02/06/2021 02:33:48 PM  * Debugger is active!
02/06/2021 02:33:48 PM  * Debugger PIN: 990-918-773
02/06/2021 02:33:53 PM 127.0.0.1 - - [06/Feb/2021 14:33:53] "[37mPOST /get_info HTTP/1.1[0m" 200 -
02/06/2021 02:33:59 PM 127.0.0.1 - - [06/Feb/2021 14:33:59] "[37mPOST /get_info HTTP/1.1[0m" 200 -
